version: '3.8'

services:
  # БД payment-service
  payment-db:
    image: postgres:15-alpine
    container_name: payment-db
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_pass
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - payment_db_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  # БД product-service
  product-db:
    image: postgres:15-alpine
    container_name: product-db
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_pass
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - product_db_data:/var/lib/postgresql/data
    networks:
      - microservices-network

volumes:
  payment_db_data:
    driver: local
  product_db_data:
    driver: local

networks:
  microservices-network:
    driver: bridge