server:
  servlet:
    context-path: /api/v1
  port: '8081'

spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    username: sa
    url: jdbc:h2:mem:paymentdb
  h2:
    console:
      path: /h2-console
      enabled: 'true'
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    org:
      springframework: INFO
    ru:
      learning:
        java:
          spring: DEBUG