server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:migration
    baseline-on-migrate: true
    baseline-version: 0

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.flywaydb: INFO
    org.springframework.jdbc.datasource.init: INFO

# Product service configuration
product-service:
  url: http://localhost:8081/api/v1