server:
  servlet:
    context-path: /api/v1
  port: 8082

product-service:
  url: http://localhost:8081/api/v1

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    driver-class-name: org.postgresql.Driver
    username: payment_user
    password: payment_pass
    url: jdbc:postgresql://payment-db:5432/payment_db
  flyway:
    enabled: true
    locations: classpath:migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework: INFO
    ru:
      learning:
        java:
          spring: DEBUG