server:
  servlet:
    context-path: /api/v1
  port: '8081'
product-service:
  url: http://localhost:8080/api/v1

spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    username: sa
    url: jdbc:h2:mem:payment_db
  flyway:
    enabled: 'true'
    locations: classpath:migration
    baseline-on-migrate: 'true'
    validate-on-migrate: 'true'
    clean-disabled: 'false'
  h2:
    console:
      path: /h2-console
      enabled: 'true'
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    org:
      springframework: INFO
    ru:
      learning:
        java:
          spring: DEBUG